name: Build Binaries

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build and commit binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.0'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build binaries
        run: |
          chmod +x scripts/build-binaries.sh
          ./scripts/build-binaries.sh

      - name: Verify binaries
        run: |
          ls -la bin/
          file bin/*

      - name: Commit and push binaries
        run: |
          git add bin/
          if git diff --cached --quiet; then
            echo "No binary changes to commit"
          else
            git commit -m "build: update binary releases

Generated from commit: ${{ github.sha }}
Build triggered by: ${{ github.actor }}

Binaries built for:
- Linux AMD64
- Linux ARM64
- macOS Intel (AMD64)
- macOS Apple Silicon (ARM64)" --allow-empty
            git push origin main
          fi
