name: binaries

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build and commit binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory /github/workspace

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.0'

      - name: Verify Go installation
        run: |
          go version
          go env

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build binaries
        run: |
          chmod +x scripts/build-binaries.sh
          ./scripts/build-binaries.sh

      - name: Verify binaries
        run: |
          ls -la bin/
          file bin/*

      - name: Commit and push binaries
        run: |
          echo "Checking git status..."
          git status --porcelain

          echo "Adding bin/ directory..."
          git add -f bin/gokku-*

          echo "Checking if there are changes to commit..."

          if git diff --cached --quiet; then
            echo "No binary changes to commit - binaries are up to date"
          else
            echo "Committing binary changes..."
            git commit -m "build: update binary releases

            Generated from commit: ${GITHUB_SHA}
            Build triggered by: ${GITHUB_ACTOR}
            Workflow run: ${GITHUB_RUN_ID}

            Binaries built for:
            - Linux AMD64
            - Linux ARM64
            - macOS Intel (AMD64)
            - macOS Apple Silicon (ARM64)" --allow-empty

            echo "Pushing changes..."
            git push origin main
            echo "Successfully pushed binary updates!"
          fi
